/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  Erc1155BatchVoucher: Erc1155BatchVoucher;
  Erc20Voucher: Erc20Voucher;
  Erc1155SingleVoucher: Erc1155SingleVoucher;
  Erc721Voucher: Erc721Voucher;
}
export interface Erc1155BatchVoucher {
  sender: string;
  receiver: string;
  token_ids: number[];
  amounts: number[];
  data: string;
}
export interface Erc20Voucher {
  receiver: string;
  amount: number;
}
export interface Erc1155SingleVoucher {
  sender: string;
  receiver: string;
  token_id: number;
  amount: number;
  data: string;
}
export interface Erc721Voucher {
  sender: string;
  receiver: string;
  token_id: number;
}
