/* eslint-disable */
/**
 * This file was automatically generated by cartesapp.template_generator.
 * DO NOT MODIFY IT BY HAND. Instead, run the generator,
 */

import { hexToBigInt, isHex, toHex } from "viem";
import {
  type InputAdded,
  type Input as CartesiInput,
  type Report as CartesiReport,
  type Output as CartesiOutput,
} from "@cartesi/viem";
import Ajv from "ajv";
import addFormats from "ajv-formats";

import {
  genericAdvanceInput,
  genericInspect,
  type IOType,
  type Models,
  IOData,
  Input,
  Output,
  type MutationOptions,
  type QueryOptions,
  CONVENTIONAL_TYPES,
  decodeToConventionalTypes,
  type AdvanceResult,
  listAdvanceResults,
  OutputWithProof,
} from "../cartesapp/utils";
import { type InspectOptions, type InspectReport } from "../cartesapp/inspect";

import * as ifaces from "./ifaces.d";


/**
 * Configs
 */

const ajv = new Ajv();
addFormats(ajv);
ajv.addFormat("biginteger", (data) => {
  if (!isHex(data)) return false;
  const dataTovalidate = hexToBigInt(data);
  return typeof dataTovalidate == "bigint";
});
const MAX_SPLITTABLE_OUTPUT_SIZE = 4194247;

/*
 * Mutations/Advances
 */


/*
 * Queries/Inspects
 */




/**
 * Models Decoders/Exporters
 */

export function decodeToModel(
  data: CartesiInput | CartesiOutput | CartesiReport | InspectReport,
  modelName: string | undefined
): any {
  if (modelName == undefined) modelName = "json";
  if (CONVENTIONAL_TYPES.includes(modelName)) {
    if ((data as CartesiOutput).decodedData)
      return decodeToConventionalTypes((data as CartesiOutput).decodedData.payload, modelName);
    return decodeToConventionalTypes(data.rawData, modelName);
  }
  const decoder = models[modelName].decoder;
  if (decoder == undefined) throw new Error("undefined decoder");
  return decoder(data);
}

export function exportToModel(data: any, modelName: string): string {
  const exporter = models[modelName].exporter;
  if (exporter == undefined) throw new Error("undefined exporter");
  return exporter(data);
}

// Voucher Erc20Voucher

export class Erc20Voucher extends OutputWithProof<ifaces.Erc20Voucher> {
  constructor(output: CartesiOutput) {
    super(models['Erc20Voucher'],output);
  }
}
export function decodeToErc20Voucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc20Voucher {
  return new Erc20Voucher(output as CartesiOutput);
}

// Voucher Erc721Voucher

export class Erc721Voucher extends OutputWithProof<ifaces.Erc721Voucher> {
  constructor(output: CartesiOutput) {
    super(models['Erc721Voucher'],output);
  }
}
export function decodeToErc721Voucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc721Voucher {
  return new Erc721Voucher(output as CartesiOutput);
}

// Voucher Erc1155SingleVoucher

export class Erc1155SingleVoucher extends OutputWithProof<ifaces.Erc1155SingleVoucher> {
  constructor(output: CartesiOutput) {
    super(models['Erc1155SingleVoucher'],output);
  }
}
export function decodeToErc1155SingleVoucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc1155SingleVoucher {
  return new Erc1155SingleVoucher(output as CartesiOutput);
}

// Voucher Erc1155BatchVoucher

export class Erc1155BatchVoucher extends OutputWithProof<ifaces.Erc1155BatchVoucher> {
  constructor(output: CartesiOutput) {
    super(models['Erc1155BatchVoucher'],output);
  }
}
export function decodeToErc1155BatchVoucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc1155BatchVoucher {
  return new Erc1155BatchVoucher(output as CartesiOutput);
}


/**
 * Model
 */

export const models: Models = {
  'Erc20Voucher': {
    ioType:"voucher",
    abiTypes:['address', 'uint256'],
    params:['receiver', 'amount'],
    decoder: decodeToErc20Voucher,
    validator: ajv.compile<ifaces.Erc20Voucher>(
      JSON.parse(
        '{"title": "Erc20Voucher", "type": "object", "properties": {"receiver": {"title": "Receiver", "type": "string"}, "amount": {"title": "Amount", "type": "integer"}}, "required": ["receiver", "amount"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'Erc721Voucher': {
    ioType:"voucher",
    abiTypes:['address', 'address', 'uint256'],
    params:['sender', 'receiver', 'token_id'],
    decoder: decodeToErc721Voucher,
    validator: ajv.compile<ifaces.Erc721Voucher>(
      JSON.parse(
        '{"title": "Erc721Voucher", "type": "object", "properties": {"sender": {"title": "Sender", "type": "string"}, "receiver": {"title": "Receiver", "type": "string"}, "token_id": {"title": "Token Id", "type": "integer"}}, "required": ["sender", "receiver", "token_id"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'Erc1155SingleVoucher': {
    ioType:"voucher",
    abiTypes:['address', 'address', 'uint256', 'uint256', 'bytes'],
    params:['sender', 'receiver', 'token_id', 'amount', 'data'],
    decoder: decodeToErc1155SingleVoucher,
    validator: ajv.compile<ifaces.Erc1155SingleVoucher>(
      JSON.parse(
        '{"title": "Erc1155SingleVoucher", "type": "object", "properties": {"sender": {"title": "Sender", "type": "string"}, "receiver": {"title": "Receiver", "type": "string"}, "token_id": {"title": "Token Id", "type": "integer"}, "amount": {"title": "Amount", "type": "integer"}, "data": {"title": "Data", "type": "string", "format": "binary"}}, "required": ["sender", "receiver", "token_id", "amount", "data"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'Erc1155BatchVoucher': {
    ioType:"voucher",
    abiTypes:['address', 'address', 'uint256[]', 'uint256[]', 'bytes'],
    params:['sender', 'receiver', 'token_ids', 'amounts', 'data'],
    decoder: decodeToErc1155BatchVoucher,
    validator: ajv.compile<ifaces.Erc1155BatchVoucher>(
      JSON.parse(
        '{"title": "Erc1155BatchVoucher", "type": "object", "properties": {"sender": {"title": "Sender", "type": "string"}, "receiver": {"title": "Receiver", "type": "string"}, "token_ids": {"title": "Token Ids", "type": "array", "items": {"type": "integer"}}, "amounts": {"title": "Amounts", "type": "array", "items": {"type": "integer"}}, "data": {"title": "Data", "type": "string", "format": "binary"}}, "required": ["sender", "receiver", "token_ids", "amounts", "data"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  };