/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  VariableCreated: VariableCreated;
  UserBalance: UserBalance;
  VariablesPayload: VariablesPayload;
  SetOperatorPayload: SetOperatorPayload;
  UserInfoPayload: UserInfoPayload;
  VariableResolved: VariableResolved;
  ResolveVariablePayload: ResolveVariablePayload;
  EditVariablesPayload: EditVariablesPayload;
  EmptyClass: EmptyClass;
  ProbabilityUpdated: ProbabilityUpdated;
  QueryVariablesPayload: QueryVariablesPayload;
  AddVariablePayload: AddVariablePayload;
  InitializePayload: InitializePayload;
}
export interface VariableCreated {
  alias: string;
  n_states: number;
  created_at: number;
}
export interface UserBalance {
  user: string;
  free_funds: number;
  expected: number;
  timestamp: number;
}
export interface VariablesPayload {
  alias: string;
}
export interface SetOperatorPayload {
  new_operator_address: string;
}
export interface UserInfoPayload {
  user_address: string;
}
export interface VariableResolved {
  alias: string;
  final_state: number;
  timestamp: number;
}
export interface ResolveVariablePayload {
  alias: string;
  state: number;
}
export interface EditVariablesPayload {
  value: number;
  fund_threshold: number;
  var_aliases: string[];
  var_states: number[];
  evidence_aliases: string[];
  evidence_states: number[];
}
export interface EmptyClass {}
export interface ProbabilityUpdated {
  alias: string;
  probabilities: number[];
  volume: number;
  volume_ss: number;
  timestamp: number;
}
export interface QueryVariablesPayload {
  var_aliases: string[];
  var_states: number[];
  evidence_aliases?: string[] | null;
  evidence_states?: number[] | null;
  value?: number | null;
  user_address?: string | null;
}
export interface AddVariablePayload {
  alias: string;
  n_states: number;
  resolve_address: string;
  cliques: CliqueAliases[];
  new_cluster: boolean;
  new_cluster_aliases: string[];
  info_url: string;
}
export interface CliqueAliases {
  aliases: string[];
}
export interface InitializePayload {
  b: number;
}
