/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface _Master_ {
  EtherEvent: EtherEvent;
  Erc1155Event: Erc1155Event;
  WalletBalance: WalletBalance;
  WithdrawErc20Voucher: WithdrawErc20Voucher;
  WithdrawErc1155BatchVoucher: WithdrawErc1155BatchVoucher;
  WithdrawErc721Voucher: WithdrawErc721Voucher;
  TransferEtherPayload: TransferEtherPayload;
  Erc20Event: Erc20Event;
  WithdrawErc1155SingleVoucher: WithdrawErc1155SingleVoucher;
  Erc721Event: Erc721Event;
  WithdrawEtherPayload: WithdrawEtherPayload;
}
export interface EtherEvent {
  timestamp: number;
  user: string;
  mod_amount: number;
  balance: number;
}
export interface Erc1155Event {
  timestamp: number;
  user: string;
  address: string;
  mod_ids: number[];
  mod_amounts: number[];
  ids: number[];
  amounts: number[];
}
export interface WalletBalance {
  ether?: number | null;
  erc20?: {
    [k: string]: number;
  } | null;
  erc721?: {
    [k: string]: number[];
  } | null;
  erc1155?: {
    [k: string]: {
      [k: string]: number;
    };
  } | null;
}
export interface WithdrawErc20Voucher {
  user: string;
  amount: number;
}
export interface WithdrawErc1155BatchVoucher {
  sender: string;
  receiver: string;
  ids: number[];
  amounts: number[];
  data: string;
}
export interface WithdrawErc721Voucher {
  sender: string;
  receiver: string;
  id: number;
}
export interface TransferEtherPayload {
  receiver: string;
  amount: number;
  exec_layer_data: string;
}
export interface Erc20Event {
  timestamp: number;
  user: string;
  address: string;
  mod_amount: number;
  balance: number;
}
export interface WithdrawErc1155SingleVoucher {
  sender: string;
  receiver: string;
  id: number;
  amount: number;
  data: string;
}
export interface Erc721Event {
  timestamp: number;
  user: string;
  address: string;
  mod_id: number;
  ids: number[];
}
export interface WithdrawEtherPayload {
  amount: number;
  exec_layer_data: string;
}
