/* eslint-disable */
/**
 * This file was automatically generated by cartesapp.template_generator.
 * DO NOT MODIFY IT BY HAND. Instead, run the generator,
 */

import { hexToBigInt, isHex, toHex } from "viem";
import {
  type InputAdded,
  type Input as CartesiInput,
  type Report as CartesiReport,
  type Output as CartesiOutput,
} from "@cartesi/viem";
import Ajv from "ajv";
import addFormats from "ajv-formats";

import {
  genericAdvanceInput,
  genericInspect,
  type IOType,
  type Models,
  IOData,
  Input,
  Output,
  type MutationOptions,
  type QueryOptions,
  CONVENTIONAL_TYPES,
  decodeToConventionalTypes,
  type AdvanceResult,
  listAdvanceResults,
  OutputWithProof,
} from "../cartesapp/utils";
import { type InspectOptions, type InspectReport } from "../cartesapp/inspect";

import * as ifaces from "./ifaces.d";


/**
 * Configs
 */

const ajv = new Ajv();
addFormats(ajv);
ajv.addFormat("biginteger", (data) => {
  if (!isHex(data)) return false;
  const dataTovalidate = hexToBigInt(data);
  return typeof dataTovalidate == "bigint";
});
const MAX_SPLITTABLE_OUTPUT_SIZE = 4194247;

/*
 * Mutations/Advances
 */

export async function withdrawEther(
    inputData: ifaces.WithdrawEtherPayload,
    options:MutationOptions
): Promise<InputAdded[] | AdvanceResult[] | unknown[]> {
  const data: WithdrawEtherPayload = new WithdrawEtherPayload(inputData);
  return await genericAdvanceInput<ifaces.WithdrawEtherPayload>(
    options,
    '0x8cf70f0b',
    data
  );
}

export async function transferEther(
    inputData: ifaces.TransferEtherPayload,
    options:MutationOptions
): Promise<InputAdded[] | AdvanceResult[] | unknown[]> {
  const data: TransferEtherPayload = new TransferEtherPayload(inputData);
  return await genericAdvanceInput<ifaces.TransferEtherPayload>(
    options,
    '0xff67c903',
    data
  );
}


/*
 * Queries/Inspects
 */




/**
 * Models Decoders/Exporters
 */

export function decodeToModel(
  data: CartesiInput | CartesiOutput | CartesiReport | InspectReport,
  modelName: string | undefined
): any {
  if (modelName == undefined) modelName = "json";
  if (CONVENTIONAL_TYPES.includes(modelName)) {
    if ((data as CartesiOutput).decodedData)
      return decodeToConventionalTypes((data as CartesiOutput).decodedData.payload, modelName);
    return decodeToConventionalTypes(data.rawData, modelName);
  }
  const decoder = models[modelName].decoder;
  if (decoder == undefined) throw new Error("undefined decoder");
  return decoder(data);
}

export function exportToModel(data: any, modelName: string): string {
  const exporter = models[modelName].exporter;
  if (exporter == undefined) throw new Error("undefined exporter");
  return exporter(data);
}

// Mutation WithdrawEtherPayload
export class WithdrawEtherPayloadInput extends Input<ifaces.WithdrawEtherPayload> {
  constructor(data: CartesiInput) {
    super(models['WithdrawEtherPayload'],data);
  }
}
export function decodeToWithdrawEtherPayloadInput(
  data: CartesiInput | CartesiOutput | CartesiReport | InspectReport,
): WithdrawEtherPayloadInput {
  return new WithdrawEtherPayloadInput(data as CartesiInput);
}
export class WithdrawEtherPayload extends IOData<ifaces.WithdrawEtherPayload> {
  constructor(data: ifaces.WithdrawEtherPayload, validate: boolean = true) {
    super(models['WithdrawEtherPayload'],data,validate);
  }
}
export function exportToWithdrawEtherPayload(data: ifaces.WithdrawEtherPayload): string {
  const dataToExport: WithdrawEtherPayload = new WithdrawEtherPayload(data);
  return dataToExport.export();
}

// Mutation TransferEtherPayload
export class TransferEtherPayloadInput extends Input<ifaces.TransferEtherPayload> {
  constructor(data: CartesiInput) {
    super(models['TransferEtherPayload'],data);
  }
}
export function decodeToTransferEtherPayloadInput(
  data: CartesiInput | CartesiOutput | CartesiReport | InspectReport,
): TransferEtherPayloadInput {
  return new TransferEtherPayloadInput(data as CartesiInput);
}
export class TransferEtherPayload extends IOData<ifaces.TransferEtherPayload> {
  constructor(data: ifaces.TransferEtherPayload, validate: boolean = true) {
    super(models['TransferEtherPayload'],data,validate);
  }
}
export function exportToTransferEtherPayload(data: ifaces.TransferEtherPayload): string {
  const dataToExport: TransferEtherPayload = new TransferEtherPayload(data);
  return dataToExport.export();
}

// Report WalletBalance

export class WalletBalance extends Output<ifaces.WalletBalance> {
  constructor(output: CartesiReport | InspectReport) {
    super(models['WalletBalance'],output);
  }
}
export function decodeToWalletBalance(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): WalletBalance {
  return new WalletBalance(output as CartesiReport);
}

// Notice EtherEvent

export class EtherEvent extends OutputWithProof<ifaces.EtherEvent> {
  constructor(output: CartesiOutput) {
    super(models['EtherEvent'],output);
  }
}
export function decodeToEtherEvent(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): EtherEvent {
  return new EtherEvent(output as CartesiOutput);
}

// Notice Erc20Event

export class Erc20Event extends OutputWithProof<ifaces.Erc20Event> {
  constructor(output: CartesiOutput) {
    super(models['Erc20Event'],output);
  }
}
export function decodeToErc20Event(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc20Event {
  return new Erc20Event(output as CartesiOutput);
}

// Notice Erc721Event

export class Erc721Event extends OutputWithProof<ifaces.Erc721Event> {
  constructor(output: CartesiOutput) {
    super(models['Erc721Event'],output);
  }
}
export function decodeToErc721Event(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc721Event {
  return new Erc721Event(output as CartesiOutput);
}

// Notice Erc1155Event

export class Erc1155Event extends OutputWithProof<ifaces.Erc1155Event> {
  constructor(output: CartesiOutput) {
    super(models['Erc1155Event'],output);
  }
}
export function decodeToErc1155Event(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): Erc1155Event {
  return new Erc1155Event(output as CartesiOutput);
}

// Voucher WithdrawErc20Voucher

export class WithdrawErc20Voucher extends OutputWithProof<ifaces.WithdrawErc20Voucher> {
  constructor(output: CartesiOutput) {
    super(models['WithdrawErc20Voucher'],output);
  }
}
export function decodeToWithdrawErc20Voucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): WithdrawErc20Voucher {
  return new WithdrawErc20Voucher(output as CartesiOutput);
}

// Voucher WithdrawErc721Voucher

export class WithdrawErc721Voucher extends OutputWithProof<ifaces.WithdrawErc721Voucher> {
  constructor(output: CartesiOutput) {
    super(models['WithdrawErc721Voucher'],output);
  }
}
export function decodeToWithdrawErc721Voucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): WithdrawErc721Voucher {
  return new WithdrawErc721Voucher(output as CartesiOutput);
}

// Voucher WithdrawErc1155SingleVoucher

export class WithdrawErc1155SingleVoucher extends OutputWithProof<ifaces.WithdrawErc1155SingleVoucher> {
  constructor(output: CartesiOutput) {
    super(models['WithdrawErc1155SingleVoucher'],output);
  }
}
export function decodeToWithdrawErc1155SingleVoucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): WithdrawErc1155SingleVoucher {
  return new WithdrawErc1155SingleVoucher(output as CartesiOutput);
}

// Voucher WithdrawErc1155BatchVoucher

export class WithdrawErc1155BatchVoucher extends OutputWithProof<ifaces.WithdrawErc1155BatchVoucher> {
  constructor(output: CartesiOutput) {
    super(models['WithdrawErc1155BatchVoucher'],output);
  }
}
export function decodeToWithdrawErc1155BatchVoucher(
  output: CartesiInput | CartesiOutput | CartesiReport | InspectReport
): WithdrawErc1155BatchVoucher {
  return new WithdrawErc1155BatchVoucher(output as CartesiOutput);
}


/**
 * Model
 */

export const models: Models = {
  'WithdrawEtherPayload': {
    ioType:"mutationPayload",
    abiTypes:['uint256', 'bytes'],
    params:['amount', 'exec_layer_data'],
    decoder: decodeToWithdrawEtherPayloadInput,
    exporter: exportToWithdrawEtherPayload,
    validator: ajv.compile<ifaces.WithdrawEtherPayload>(
      JSON.parse(
        '{"title": "WithdrawEtherPayload", "type": "object", "properties": {"amount": {"title": "Amount", "type": "integer"}, "exec_layer_data": {"title": "Exec Layer Data", "type": "string", "format": "binary"}}, "required": ["amount", "exec_layer_data"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'TransferEtherPayload': {
    ioType:"mutationPayload",
    abiTypes:['bytes32', 'uint256', 'bytes'],
    params:['receiver', 'amount', 'exec_layer_data'],
    decoder: decodeToTransferEtherPayloadInput,
    exporter: exportToTransferEtherPayload,
    validator: ajv.compile<ifaces.TransferEtherPayload>(
      JSON.parse(
        '{"title": "TransferEtherPayload", "type": "object", "properties": {"receiver": {"title": "Receiver", "type": "string", "format": "binary"}, "amount": {"title": "Amount", "type": "integer"}, "exec_layer_data": {"title": "Exec Layer Data", "type": "string", "format": "binary"}}, "required": ["receiver", "amount", "exec_layer_data"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'WalletBalance': {
    ioType:"report",
    abiTypes:[],
    params:['ether', 'erc20', 'erc721', 'erc1155'],
    decoder: decodeToWalletBalance,
    validator: ajv.compile<ifaces.WalletBalance>(
      JSON.parse(
        '{"title": "WalletBalance", "type": "object", "properties": {"ether": {"title": "Ether", "type": "integer"}, "erc20": {"title": "Erc20", "type": "object", "additionalProperties": {"type": "integer"}}, "erc721": {"title": "Erc721", "type": "object", "additionalProperties": {"type": "array", "items": {"type": "integer"}}}, "erc1155": {"title": "Erc1155", "type": "object", "additionalProperties": {"type": "object", "additionalProperties": {"type": "integer"}}}}}'
      )
    )
  },
  'EtherEvent': {
    ioType:"noticeHeader",
    abiTypes:['uint64', 'address', 'int256', 'uint256'],
    params:['timestamp', 'user', 'mod_amount', 'balance'],
    decoder: decodeToEtherEvent,
    validator: ajv.compile<ifaces.EtherEvent>(
      JSON.parse(
        '{"title": "EtherEvent", "type": "object", "properties": {"timestamp": {"title": "Timestamp", "type": "integer"}, "user": {"title": "User", "type": "string"}, "mod_amount": {"title": "Mod Amount", "type": "integer"}, "balance": {"title": "Balance", "type": "integer"}}, "required": ["timestamp", "user", "mod_amount", "balance"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'Erc20Event': {
    ioType:"noticeHeader",
    abiTypes:['uint64', 'address', 'address', 'int256', 'uint256'],
    params:['timestamp', 'user', 'address', 'mod_amount', 'balance'],
    decoder: decodeToErc20Event,
    validator: ajv.compile<ifaces.Erc20Event>(
      JSON.parse(
        '{"title": "Erc20Event", "type": "object", "properties": {"timestamp": {"title": "Timestamp", "type": "integer"}, "user": {"title": "User", "type": "string"}, "address": {"title": "Address", "type": "string"}, "mod_amount": {"title": "Mod Amount", "type": "integer"}, "balance": {"title": "Balance", "type": "integer"}}, "required": ["timestamp", "user", "address", "mod_amount", "balance"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'Erc721Event': {
    ioType:"noticeHeader",
    abiTypes:['uint64', 'address', 'address', 'int256', 'uint256[]'],
    params:['timestamp', 'user', 'address', 'mod_id', 'ids'],
    decoder: decodeToErc721Event,
    validator: ajv.compile<ifaces.Erc721Event>(
      JSON.parse(
        '{"title": "Erc721Event", "type": "object", "properties": {"timestamp": {"title": "Timestamp", "type": "integer"}, "user": {"title": "User", "type": "string"}, "address": {"title": "Address", "type": "string"}, "mod_id": {"title": "Mod Id", "type": "integer"}, "ids": {"title": "Ids", "type": "array", "items": {"type": "integer"}}}, "required": ["timestamp", "user", "address", "mod_id", "ids"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'Erc1155Event': {
    ioType:"noticeHeader",
    abiTypes:['uint64', 'address', 'address', 'int256[]', 'int256[]', 'uint256[]', 'uint256[]'],
    params:['timestamp', 'user', 'address', 'mod_ids', 'mod_amounts', 'ids', 'amounts'],
    decoder: decodeToErc1155Event,
    validator: ajv.compile<ifaces.Erc1155Event>(
      JSON.parse(
        '{"title": "Erc1155Event", "type": "object", "properties": {"timestamp": {"title": "Timestamp", "type": "integer"}, "user": {"title": "User", "type": "string"}, "address": {"title": "Address", "type": "string"}, "mod_ids": {"title": "Mod Ids", "type": "array", "items": {"type": "integer"}}, "mod_amounts": {"title": "Mod Amounts", "type": "array", "items": {"type": "integer"}}, "ids": {"title": "Ids", "type": "array", "items": {"type": "integer"}}, "amounts": {"title": "Amounts", "type": "array", "items": {"type": "integer"}}}, "required": ["timestamp", "user", "address", "mod_ids", "mod_amounts", "ids", "amounts"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'WithdrawErc20Voucher': {
    ioType:"voucher",
    abiTypes:['address', 'uint256'],
    params:['user', 'amount'],
    decoder: decodeToWithdrawErc20Voucher,
    validator: ajv.compile<ifaces.WithdrawErc20Voucher>(
      JSON.parse(
        '{"title": "WithdrawErc20Voucher", "type": "object", "properties": {"user": {"title": "User", "type": "string"}, "amount": {"title": "Amount", "type": "integer"}}, "required": ["user", "amount"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'WithdrawErc721Voucher': {
    ioType:"voucher",
    abiTypes:['address', 'address', 'uint256'],
    params:['sender', 'receiver', 'id'],
    decoder: decodeToWithdrawErc721Voucher,
    validator: ajv.compile<ifaces.WithdrawErc721Voucher>(
      JSON.parse(
        '{"title": "WithdrawErc721Voucher", "type": "object", "properties": {"sender": {"title": "Sender", "type": "string"}, "receiver": {"title": "Receiver", "type": "string"}, "id": {"title": "Id", "type": "integer"}}, "required": ["sender", "receiver", "id"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'WithdrawErc1155SingleVoucher': {
    ioType:"voucher",
    abiTypes:['address', 'address', 'uint256', 'uint256', 'bytes'],
    params:['sender', 'receiver', 'id', 'amount', 'data'],
    decoder: decodeToWithdrawErc1155SingleVoucher,
    validator: ajv.compile<ifaces.WithdrawErc1155SingleVoucher>(
      JSON.parse(
        '{"title": "WithdrawErc1155SingleVoucher", "type": "object", "properties": {"sender": {"title": "Sender", "type": "string"}, "receiver": {"title": "Receiver", "type": "string"}, "id": {"title": "Id", "type": "integer"}, "amount": {"title": "Amount", "type": "integer"}, "data": {"title": "Data", "type": "string", "format": "binary"}}, "required": ["sender", "receiver", "id", "amount", "data"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  'WithdrawErc1155BatchVoucher': {
    ioType:"voucher",
    abiTypes:['address', 'address', 'uint256[]', 'uint256[]', 'bytes'],
    params:['sender', 'receiver', 'ids', 'amounts', 'data'],
    decoder: decodeToWithdrawErc1155BatchVoucher,
    validator: ajv.compile<ifaces.WithdrawErc1155BatchVoucher>(
      JSON.parse(
        '{"title": "WithdrawErc1155BatchVoucher", "type": "object", "properties": {"sender": {"title": "Sender", "type": "string"}, "receiver": {"title": "Receiver", "type": "string"}, "ids": {"title": "Ids", "type": "array", "items": {"type": "integer"}}, "amounts": {"title": "Amounts", "type": "array", "items": {"type": "integer"}}, "data": {"title": "Data", "type": "string", "format": "binary"}}, "required": ["sender", "receiver", "ids", "amounts", "data"]}'.replace(
          /integer/g,
          'string","format":"biginteger'
        )
      )
    )
  },
  };